/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@class INTListViewController, UIWindow;

@interface INTAppDelegate : UIResponder <UIApplicationDelegate>
{
    UIWindow *_window;
    INTListViewController *designTechnologyViewController;
    INTListViewController *newsPoliticsViewController;
    INTListViewController *tvEntertainmentViewController;
    INTListViewController *sportsViewController;
}

@property(retain, nonatomic) INTListViewController *sportsViewController; // @synthesize sportsViewController;
@property(retain, nonatomic) INTListViewController *tvEntertainmentViewController; // @synthesize tvEntertainmentViewController;
@property(retain, nonatomic) INTListViewController *newsPoliticsViewController; // @synthesize newsPoliticsViewController;
@property(retain, nonatomic) INTListViewController *designTechnologyViewController; // @synthesize designTechnologyViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;

- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)showSavedModal;

@end

