/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface INTAnimationManager : NSObject
{
}

+ (float)bounceOut:(float)arg1;
+ (id)bounceOutAnimationFromValue:(float)arg1 toValue:(float)arg2 path:(id)arg3;
+ (void)bounceViewVertically:(id)arg1 toValue:(float)arg2 completion:(id)arg3;
+ (void)bounceViewHorizontally:(id)arg1 toValue:(float)arg2 completion:(id)arg3;
+ (void)pulseView:(id)arg1 completion:(id)arg2;

@end

