/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@class NSMutableArray, NSURL, UIColor, UIImageView, UITableView, UIView;

@interface INTListViewController : UIViewController <UIAlertViewDelegate, UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate>
{
    NSMutableArray *items;
    UIImageView *tabBar;
    NSMutableArray *itemsMeta;
    unsigned int index;
    NSURL *feedURL;
    UIColor *color;
    UITableView *tv;
    UIView *refreshHeaderView;
    UIImageView *refreshReloadIcon;
    UIImageView *refreshCheckmarkIcon;
    BOOL isLoading;
    BOOL isDragging;
}

@property BOOL isDragging; // @synthesize isDragging;
@property BOOL isLoading; // @synthesize isLoading;
@property(retain) UIImageView *refreshCheckmarkIcon; // @synthesize refreshCheckmarkIcon;
@property(retain) UIImageView *refreshReloadIcon; // @synthesize refreshReloadIcon;
@property(retain) UIView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain) UITableView *tv; // @synthesize tv;
@property(retain) UIColor *color; // @synthesize color;
@property(retain) NSURL *feedURL; // @synthesize feedURL;
@property unsigned int index; // @synthesize index;
@property(retain) NSMutableArray *itemsMeta; // @synthesize itemsMeta;
@property(retain) UIImageView *tabBar; // @synthesize tabBar;
@property(retain) NSMutableArray *items; // @synthesize items;

- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)pulseThisIcon;
- (void)viewWillAppear:(BOOL)arg1;
- (void)calculateMetadata;
- (void)itemsArrived:(id)arg1;
- (void)hideTableViewWithCompletion:(id)arg1;
- (void)showTableViewWithCompletion:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)stopLoading;
- (void)startLoading;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tappedTab3:(id)arg1;
- (void)tappedTab2:(id)arg1;
- (void)tappedTab1:(id)arg1;
- (void)tappedTab0:(id)arg1;
- (void)setupTabBar;
- (void)loadView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)handleLongPress:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 feedURL:(id)arg3 title:(id)arg4 index:(unsigned int)arg5 color:(id)arg6;

@end

