/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

#import <MessageUI/MessageUI.h>

@class NSURL, UIBarButtonItem, UIWebView;

@interface SVWebViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate, MFMailComposeViewControllerDelegate>
{
    unsigned int availableActions;
    NSURL *URL;
    UIWebView *mainWebView;
    UIBarButtonItem *backBarButtonItem;
    UIBarButtonItem *forwardBarButtonItem;
    UIBarButtonItem *refreshBarButtonItem;
    UIBarButtonItem *stopBarButtonItem;
    UIBarButtonItem *actionBarButtonItem;
}

@property(retain, nonatomic) UIWebView *mainWebView; // @synthesize mainWebView;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL;
@property(nonatomic) unsigned int availableActions; // @synthesize availableActions;

- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)doneButtonClicked:(id)arg1;
- (void)actionButtonClicked:(id)arg1;
- (void)stopClicked:(id)arg1;
- (void)reloadClicked:(id)arg1;
- (void)goForwardClicked:(id)arg1;
- (void)goBackClicked:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)updateToolbarItems;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithURL:(id)arg1;
- (id)initWithAddress:(id)arg1;
@property(readonly, nonatomic) UIBarButtonItem *actionBarButtonItem; // @synthesize actionBarButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *stopBarButtonItem; // @synthesize stopBarButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *refreshBarButtonItem; // @synthesize refreshBarButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *forwardBarButtonItem; // @synthesize forwardBarButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem;

@end

